### ISSUE TITLE
Invalid JVM Options

### ISSUE THREAD

**Issue by neuromancer-es** [alvistack/ansible-role-jira#10]
**Deployment on Debian 10**
_Opened a pull request for your reference  on the changes made  in order to make it work_

After successful deployment, I'm unable to start Jira.
IT complains about  certain options in setenv.sh

- Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
- Unrecognized VM option 'NumberOfGCLogFiles=5'
- Unrecognized VM option 'GCLogFileSize=20M'
- Unrecognized VM option 'PrintGCDateStamps'

It  also complains regarding:
[warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:/opt/atlassian/jira/logs/atlassian-jira-gc-%t.log instead.

**Comment by hswong3i** [comment]
We are supporting AdoptOpenJDK 8 with our default variable combation. Are you using JDK 11?

**Comment by neuromancer-es** [comment]
Indeed I'm using version 11,
I used this playbook on a fresh machine. I presume it was the playbook that installed version 11.
Perhaps it's due to the fact that Debian 10 has it as default apt package?

**Comment by hswong3i** [comment]
We are now using AdoptOpenJDK 8 for JIRA, please check: 
- https://github.com/alvistack/ansible-role-jira/blob/master/molecule/debian-10/group_vars/all/99-molecule.yml#L17
- https://github.com/alvistack/ansible-role-jira/blob/master/molecule/default/converge.yml
- https://github.com/alvistack/ansible-role-openjdk/blob/master/defaults/main.yml

**Comment by neuromancer-es** [comment]
Indeed Debian is specifying version 8 on it's default molecule. I'm using tower to deploy and for some reason it gathered the version 11 from the openjdk role.

In any case, seems unrelated to the playbook, I'll investigate how to properly reference to version 8
Maybe a reference the need for version 8 might be useful for others, the other open issue sounds like it could be coming from the same openjdk issue.

Thank you again!!

**Comment by hswong3i** [comment]
Fixed by https://github.com/alvistack/ansible-role-jira/commit/86df9c7f28511fe7af05da9681726b8e23b4395e
