### ISSUE TITLE
Galaxy don't have version 4.6.x

### ISSUE THREAD

**Issue by RogerSik** [alvistack/ansible-role-jira#13]
Like (earlier) in the Confluence role ([issue](https://github.com/alvistack/ansible-role-confluence/issues/8)) the [galaxy don't ](https://galaxy.ansible.com/alvistack/jira) have the newest version.

**Comment by hswong3i** [comment]
Temporarily fixed by manually import; import logic now triggered by master branch, which will be cron job per weekly ;-)
