### ISSUE TITLE
TASK [alvistack.jira : useradd] usermod: user jira is currently used by process <processID>

### ISSUE THREAD

**Issue by vvsco** [alvistack/ansible-role-jira#14]
error while running task useradd

Ubuntu 20.04 clean
selected 9.4 jira version

**Comment by hswong3i** [comment]
Shouldn't be that, see https://github.com/alvistack/ansible-role-jira/blob/master/tasks/main.yml#L56-L70

I didn't specify corresponding uid/gid with any number, it should pick up automatically based on your running OS default style, e.g. Ubuntu will choose from 999 -> 998 -> 997 etc.

**Comment by hswong3i** [comment]
But https://gitlab.com/alvistack/ansible-role-jira/-/jobs/3466258997 should passed with Ubuntu 20.04 :-S
