### ISSUE TITLE
Java 11 compatibilty

### ISSUE THREAD

**Issue by JulieCztd** [alvistack/ansible-role-jira#2]
Jus to inform you, some options you used for Java8 don't exist anymore in Java11. 
And the version of the apache felix framework you are currently using also generates errors with java11. These erros were fixed in the 6.0.2version.
(This was tested   when installing jira with your code on a Ubuntu18.04 Server where by default you have Java10. And it seems better to upgrade Java to 11 than to downgrade to 8.)

**Comment by hswong3i** [comment]
We use Java 8 during Ubuntu 18.04 test

https://github.com/alvistack/ansible-role-jira/blob/master/molecule/ubuntu-18.04/playbook.yml

And Java 11 is not yet supported by JIRA

**Comment by JulieCztd** [comment]
It is now supported by Jira, because when I had neither 8 or 11, it was proposing both. It just requests some changes but it works just fine.
But yes I saw that, and it worked really well with Java8.

**Comment by hswong3i** [comment]
Should not yet support Java 11

https://confluence.atlassian.com/adminjiraserver/supported-platforms-938846830.html


Should be after JIRA 8.1, after Q1

https://developer.atlassian.com/blog/2019/01/december-update-upcoming-breaking-changes-across-server-products/

**Comment by hswong3i** [comment]
P.S. I will usually upgrade all my Atlassian related role Java support, after ALL of them already support Java 11, else usually VERY buggy :-(

**Comment by JulieCztd** [comment]
Yes of course, I understand. But seems to work with your version of Jira under Java11. And I only wanted to give you the info. If you want to make it Java 11 compatible, you don't have a lot of changes to do :)
But that's true that it's not listed in the supported version on their website.

**Comment by hswong3i** [comment]
Fixed by https://github.com/alvistack/ansible-role-jira/commit/86df9c7f28511fe7af05da9681726b8e23b4395e
