### ISSUE TITLE
Java 11 requires changes to Garbage Collection Log settings

### ISSUE THREAD

**Issue by hnk** [alvistack/ansible-role-jira#6]
Per [this kb article](https://confluence.atlassian.com/jirakb/garbage-collection-log-settings-for-jira-when-using-java-version-11-981148994.html) using java 11 requires different settings for GC logging in setenv.sh. This line is affected : [setenv.sh+118](https://github.com/alvistack/ansible-role-jira/blob/8827259cd751eeea4fc9eddeade82493a2b9bc85/templates/opt/atlassian/jira/bin/setenv.sh.j2#L118)

I am wondering if a separate setenv.sh.j2 template should be created and used if java 11 is installed and how this could be checked.

How do you solve this issue when using [alvistack/openjdk](https://github.com/alvistack/ansible-role-openjdk)?

**Comment by hnk** [comment]
Sorry, just realized that this has been talked about in another issue #2. Closing.

**Comment by hswong3i** [comment]
I am still waiting for [Bamboo](https://confluence.atlassian.com/bamboo/supported-platforms-289276764.html) and [Fisheye](https://confluence.atlassian.com/fisheye/supported-platforms-960155252.html) for Java 11 support ;-S

**Comment by hswong3i** [comment]
Fixed by https://github.com/alvistack/ansible-role-jira/commit/86df9c7f28511fe7af05da9681726b8e23b4395e
